### ISSUE TITLE
Mod Incompatibility: Renai Transportation

### ISSUE THREAD

**Issue by NinjaDuckie** [ProfessorConfundus/PCs-Infinite-Ammo#5]
Activating the [weird & wacky transportation mod](https://mods.factorio.com/mod/RenaiTransportation) causes the game to crash on attempting to load PCIA, with a warning that line 83 of items.lua tries to call a nil value. It's also not happy with the data-final-fixes.lua file. I'm no LUA coder but I'm guessing this is because Renai has a function for launching objects from crashing trains, and treating launched ammo types as incoming projectiles (which is WILD). All I know for sure is that their final-fixes file contains a LOT of messing with ammo code and as you say on your FAQ page that _may_ cause incompatibilities.

I did play around awhile with mod settings to see if there was a setting on Renai that could be turned off which would allow the mods to work together, but didn't get anywhere. If you _can_ provide a fix then thanks! But no big deal if you can't or won't.

**Comment by ProfessorConfundus** [comment]
Hi!

Thanks for raising this issue. First, to help me with debugging the issue, can you please:
- Send me a _screenshot_ of the error message please, it has important traceback deets that you haven't included in your message.
- And secondly, please tell me _when_ the error occurred. Did it occur on trying to start/reload the entire game, or only when loading a save, or somewhere else entirely?

Also, thanks for doing some testing with the conflicting mod, it saves me a lot of time and struggle!

**Comment by ProfessorConfundus** [comment]
Also, it appears the mod ports page you linked to is not present? Please double check it for spelling errors and typos.

**Comment by NinjaDuckie** [comment]
Apparently putting a slash on the end of the mod link breaks it? [Fixed link in original and here.](https://mods.factorio.com/mod/RenaiTransportation) Not sure how the slash got in there.

Error occurred right on game init after enabling the mod. Tested by disabling all other mods and only enabling Renai, PCIA (and the Rusty's Locale mod required for it).

[Uploaded an image of the error.](https://i.imgur.com/ZMxIr6N.jpg)

**Comment by ProfessorConfundus** [comment]
Thank you for the response! 
This is all I needed, and I can already see the problem: The mod is trying to reference a recipe for some ammo that doesn't have a recipe (or one of those weird, rare recipes like the uranium processing recipe)
I'm going to rework the recipe-generating system and see if that fixes the problem. I'll be sure to tell you when I've updated the mod with the fix. 
Thanks again for reporting this bug!

**Comment by ProfessorConfundus** [comment]
@NinjaDuckie the mod has been updated, and the issue is (or at least, should be) fixed! If you happen to find any more problems, or the issue has not been fixed for you, please create a new issue.
Again, I can't thank you enough for reporting the bug! You even led me to the solution for another active flaw with the mod!
