### ISSUE TITLE
Error message during start

### ISSUE THREAD

**Issue by berserker465** [ProfessorConfundus/PCs-Infinite-Ammo#6]
Factorio version 1.1.57

Error:
Failed to load mods: Error while loading item prototype "pc-unlimited-uranium-rounds-magazine" (ammo): Value (inf) outside of range. The data type allows values from -((huge number)) to ((huge number)) in propriety tree a ROOT.ammo.pc-unlimited-uranium-rounds-magazine.magazine_size

**Comment by berserker465** [comment]
Update:
Downgrading Factorio to version 1.1.53 fixed the issue (for now)

**Comment by ProfessorConfundus** [comment]
Hi! Thanks for reporting the issue.
Could you please send a _screenshot_ of the error? It includes some small little details that could help solve the problem.

**Comment by berserker465** [comment]
Sure 
![Clipboard02](https://user-images.githubusercontent.com/23174269/161333574-709919be-8897-4293-80ca-a30817c13e3e.png)

**Comment by ProfessorConfundus** [comment]
Thanks! I think I see the issue: The Factorio developers have changed the limit of the magazine size from infinite to the 128-bit integer limit. I'll have to release an update that changes the magazine size to said 128-bit integer limit.
It's still practically infinite, like how would oneself use 340 undecillion bullets?
Anyway, thanks again for reporting! A patch should be out in the next 12 hours.

**Comment by berserker465** [comment]
Thanks for the quick response :)

**Comment by ProfessorConfundus** [comment]
A hotfix has been released, which (should) fix the bug. It is a bit of a bodge, so it will need improvement later, and technically, the ammo is no longer infinite, but practically, it is.
Again, thank you so much for reporting this issue! If you encounter this bug (or any other bug) again, please make a new issue. Cheers!
