### ISSUE TITLE
Small UI issue

### ISSUE THREAD

**Issue by berserker465** [ProfessorConfundus/PCs-Infinite-Ammo#7]
![Clipboard01](https://user-images.githubusercontent.com/23174269/161354686-5ed3f2d6-431c-4c26-aa72-8969e532d31c.png)

The green lines that represent the quantity kinda overtake the whole length of the screen now ^^

**Comment by berserker465** [comment]
Oh well I updated Factorio to the latest version (1.1.57) and there's no UI issue there, so all good ~

**Comment by ProfessorConfundus** [comment]
Ah, that's relieving, because that would've been a issue that would be a royal pain in the behind to fix, heh. Anyway, thanks for that, maybe I'll increase the min game version to prevent further confused players, heh.
